// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS2SuB13uLWIv-g9PU_kxFzhbA76F_c8U',
    appId: '1:95459701701:android:6f5adcd01feddb1c2e11ac',
    messagingSenderId: '95459701701',
    projectId: 'ensurecritical-c-1488204492384',
    databaseURL: 'https://ensurecritical-c-1488204492384.firebaseio.com',
    storageBucket: 'ensurecritical-c-1488204492384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTWbhCimcwXcTzYie6oFF8-gUzmGz5fac',
    appId: '1:95459701701:ios:e59515b0c953aaef2e11ac',
    messagingSenderId: '95459701701',
    projectId: 'ensurecritical-c-1488204492384',
    databaseURL: 'https://ensurecritical-c-1488204492384.firebaseio.com',
    storageBucket: 'ensurecritical-c-1488204492384.firebasestorage.app',
    androidClientId: '95459701701-co5h6gtsctu1i4f22533u808c11k1c6q.apps.googleusercontent.com',
    iosBundleId: 'com.location.taxiBooking',
  );
}
